### ISSUE TITLE
cp: 无法获取'out/target/product/generic_arm64/obj_arm/SHARED_LIBRARIES/afl-llvm-rt_intermediates/llvm_mode/afl-llvm-rt.o.o' 的文件状态(stat): 没有那个文件或目录

### ISSUE THREAD

**Issue by pppdddxxx** [ele7enxxh/android-afl#14]
Hi, I have a problem when i compile the android-afl project.

===================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=6.0.1
TARGET_PRODUCT=aosp_arm64
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a15
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_BUILD_TYPE=release
BUILD_ID=MMB29K
OUT_DIR=out
======================================

...
...
Export includes file: android-afl/Android.mk -- out/target/product/generic_arm64/obj/SHARED_LIBRARIES/afl-llvm-rt_intermediates/export_includes
target Strip: afl-llvm-rt (out/target/product/generic_arm64/obj/lib/afl-llvm-rt.so)
Install: out/target/product/generic_arm64/system/lib64/afl-llvm-rt.so
**cp: 无法获取'out/target/product/generic_arm64/obj_arm/SHARED_LIBRARIES/afl-llvm-rt_intermediates/llvm_mode/afl-llvm-rt.o.o' 的文件状态(stat): 没有那个文件或目录
build/core/base_rules.mk:559: recipe for target 'out/target/product/generic_arm64/system/lib64/afl-llvm-rt.so' failed**
make: *** [out/target/product/generic_arm64/system/lib64/afl-llvm-rt.so] Error 1
make: *** Deleting file 'out/target/product/generic_arm64/system/lib64/afl-llvm-rt.so'
make: Leaving directory '/home/ppc/source'

#### make failed to build some targets (7 seconds) ####

How to fix it ,thanks!

**Comment by ele7enxxh** [comment]
afl-llvm-rt.o.o应该在你的out目录下，你可以搜索一下，然后手动copy，或者修改android.mk的cp部分的代码

**Comment by pppdddxxx** [comment]
Oh! I got it, thanks!
