### ISSUE TITLE
afl-llvm-rt.o file arm version

### ISSUE THREAD

**Issue by dragonltx** [ele7enxxh/android-afl#3]
/out/host/linux-x86/afl directory doesn't contain afl-llvm-rt.o of arm version,and the bin build  with this afl-llvm-rt.o doesn't work fine at android

**Comment by ele7enxxh** [comment]
it will generate a bin of target version, so if you want get afl-llvm-rt.o of arm version, you should compile the Android source code for arm. 
e.g.
`cd aosp`
`source build/envsetup.sh`
`lunch aosp_arm-eng`
`make -j8`
'cd anroid-afl'
'mm -B'

**Comment by dragonltx** [comment]
oh it's ok now!
As i just lunch aosp_shamu-userdebug,so the afp-llvm-rt.o is not the arm version！
