### ISSUE TITLE
issue with export environment 

### ISSUE THREAD

**Issue by vah13** [ele7enxxh/android-afl#4]
hi.
thank you for this fork.

have question about environment.
cloned and installed android-afl (
git clone ***
make & make install
)

after use export CC=afl-gcc and export CXX=afl-g++, but in compilation  time Ubuntu choose default gcc compilation and don't use afl-gcc. how i can fix it, what I do wrong?

thank you

**Comment by ele7enxxh** [comment]
you should see file "README.md".

**Comment by vah13** [comment]
OK, I do it. 
have other question :-) 
how I can compile android for x86 or x64 platform?
