### ISSUE TITLE
CANNOT LINK EXECUTABLE "./crash": /data/local/tmp/crash: has text relocations

### ISSUE THREAD

**Issue by juneJuly** [ele7enxxh/android-afl#8]
i complie crash in AOSP/android-afl/android-test/  with command "TEST_GCC_ARM=true mm -B"
and i got crash file in (TARGET_OUT)/target/product/shamu/system/bin/crash.
then, i adb push crash to my phone, run the crash file, and got an error as below :

```
134|shamu:/data/local/tmp # ./crash 12
CANNOT LINK EXECUTABLE "./crash": /data/local/tmp/crash: has text relocations
Aborted
```

what is the problem?

**Comment by juneJuly** [comment]
nexus 6
androidN

**Comment by GeneBlue** [comment]
try cmd:TEST_CLANG_FAST_ARM=true mm -B

**Comment by juneJuly** [comment]
@GeneBlue thanks, that's work for me!
